package br.com.zipext.plr.enums;

public enum EnumProperty {
	XLS_TEMPLATE_FOLHA_META_PATH,
	XLS_TEMPLATE_INDICADORES_PATH,
	XLS_TEMPLATE_COLABORADORES_PATH,
	XLS_TEMPLATE_CARGOS_PATH,
	XLS_TEMPLATE_EQUIVALENCIAS_PATH,
	XLS_TEMPLATE_DIRETORIAS_PATH,
	XLS_TEMPLATE_FILIAIS_PATH,
	XLS_TEMPLATE_TIMES_PATH,
	XLS_TEMPLATE_TIPOS_META_PATH,
	XLS_TEMPLATE_TIPOS_MEDICAO_PATH,
	XLS_TEMPLATE_FORMULA_PATH,
	XLS_TEMPLATE_FREQUENCIA_MEDICAO_PATH,
	XLS_TEMPLATE_ESCALONAMENTO_PATH,
	XLS_TEMPLATE_FOLHAS_METAS_MENSAIS_PATH,
	XLS_TEMPLATE_CONSULTA_FOLHAS_METAS_PATH,
	XLS_TEMPLATE_ESCALONAMENTO_QUALI_PATH,
	APP_EXTERNAL_HOST_IP,
	APP_INTERNAL_HOST_IP
}
