package br.com.zipext.plr.enums;

public enum EnumProperty {
	XLS_TEMPLATE_FOLHA_META_PATH,
	XLS_TEMPLATE_INDICADORES_PATH,
	XLS_TEMPLATE_COLABORADORES_PATH,
	XLS_TEMPLATE_CARGOS_PATH,
	XLS_TEMPLATE_EQUIVALENCIAS_PATH,
	XLS_TEMPLATE_DIRETORIAS_PATH,
	XLS_TEMPLATE_FILIAIS_PATH,
	XLS_TEMPLATE_TIMES_PATH,
	APP_EXTERNAL_HOST_IP,
	APP_INTERNAL_HOST_IP
}
